### ISSUE TITLE
Changing HTML source doesn't update model

### ISSUE THREAD

**Issue by riyunoa** [chymz/ng2-ckeditor#152]
Not sure if this is a bug or feature - when you change the HTML source in the editor, the model is not updated until you click the Source button again to turn off HTML editing. OnChange is also not triggered. Would be nice if updating the HTML would cause the model to be updated without having to click the Source button again.

Steps to reproduce:
https://embed.plnkr.co/hnB0R3/
1. Click "Source" to turn on html editing, type something in the editor. Notice that the output hasn't changed.
3. Click "Source" to turn off html editing. The output does update.

**Comment by kzimny** [comment]
Hi, no this is not possible at all. Please check the reported bug in [ckeditor forum](https://dev.ckeditor.com/ticket/12031), which has been closed because it's invalid. Change event was defined only for WYSIWYG mode. You can use the (change)="onChange($event)" event from ckeditor in order to get the changes when you change from source code to wysiwyg mode. Sorry, but this is not ng2-ckeditor issue. Please close this issue.
