### ISSUE TITLE
 Add a custom plungin in angular2.

### ISSUE THREAD

**Issue by HalShaw** [chymz/ng2-ckeditor#159]
I have a written plungin named dynamicVar,it was written with js,but I need to use it in angular2. 
I followed http://cdn.ckeditor.com/ and configed my ts file like this,it worked without the customed plungin configed,but it didn't work after I configed it.

CKEDITOR.plugins.addExternal( 'dynamicVar', '/libs/ckeditor/plugins/dynamicVar', 'plugin.js' );
CKEDITOR.replace("editor1",
	{
		extraPlugins: 'dynamicVar'
	 }
);

**Comment by kzimny** [comment]
Hi,
To enable an extra plugin from a local folder while using CKEditor CDN, CKEDITOR.plugins.addExternal() must be called first so that CKEditor knew from where to load the plugin.
What does this mean?
Load the plugin in your _Layout.cshtml file just after the ckeditor script reference as follows:
```js
<script src="https://cdn.ckeditor.com/4.5.11/full-all/ckeditor.js"></script>
<script type="text/javascript">
	CKEDITOR.plugins.addExternal('youtube', '/plugins/youtube/', 'plugin.js');
</script>
```
Download the plugin from [here ](https://ckeditor.com/cke4/addon/youtube) and extract the content to: root/plugins/youtube directory. At last add the extraPlugins name to the config file as follows:
```js
this.ckeConfig = {
	height: 500,
	extraPlugins: "youtube"
};
```
That's it!

**Comment by HalShaw** [comment]
I did like this,but it's still not working.It returns a 404 error,but I am sure the path is right because I can get the pics from that path in my project.But I found a way to rewrite that plugin.Thanks a lot.

**Comment by nicktobolski** [comment]
I used this with a custom plugin and found this very helpful. Could be useful in the docs. Thanks @kzimny
