### ISSUE TITLE
Inclusion of js file in index.html impacting the loading time.

### ISSUE THREAD

**Issue by sks40gb** [chymz/ng2-ckeditor#185]
As per installation,  it has been mentioned that js file should be added in index.html. This will increase the initial loading. Even for those pages which does not require the RTE.

This Editor JS file should be added as module so that angular can optimize the size of file and the dependency for components which is using the RTE.

**Comment by kzimny** [comment]
Well, that's a controversial suggestion because ng2-ckeditor is declared as a component and is up to you how you use them. In your own project there are maybe other scripts which need to be included on first page load for instance FileSaver, GoogleMaps, GoogleRecaptscha and so on. Why not prepare an [ExternalScriptService ](https://stackoverflow.com/a/42766146) class with [ScriptLoaderService](https://stackoverflow.com/a/44016611) class and load all the scripts when they are needed and not load them all on initial page load? The next question is, why ng2-ckeditor should solve all your application problems?
