### ISSUE TITLE
ckeditorInit runs on every check

### ISSUE THREAD

**Issue by arlowhite** [chymz/ng2-ckeditor#204]
https://github.com/chymz/ng2-ckeditor/blob/df537ca86d8586ab3d9879719c11988b364c19b9/src/ckeditor.component.ts#L107

ckeditorInit is run on every Angular `ngDoCheck()`
Shouldn't ckeditorInit just run once?

**Comment by kzimny** [comment]
This is a good question. The ng2-ckeditor is initializes in ngAfterViewInit(). I can not determine any changes without ngAfterViewChecked() method. @chymz: why did you implement ngAfterViewChecked() method which fires on every content change?

**Comment by chymz** [comment]
A bit old but this hook is used to fix ng2-ckeditor in md-tabs. In some cases, ngViewAfterInit is not enough to init CKEditor instance (see #124)

So ckeditorInit is called multiple times but stopped by:

```ts
      // Check textarea exists
      if (this.instance || !this.documentContains(this.host.nativeElement)) {
        return;
      }
```
As I said it's a dirty fix (https://github.com/chymz/ng2-ckeditor/issues/124#issuecomment-310656475) If someone have a better idea, I'll take the PR ;)

**Comment by kzimny** [comment]
Thanks, I don't have better idea. According to me no changes are required because of `if (this.instance || !this.documentContains(this.host.nativeElement))`. However, I believe that the problem with md-tabs should be solved in own application as mentioned [here](https://github.com/chymz/ng2-ckeditor/issues/124#issuecomment-331526587) and [here](https://github.com/chymz/ng2-ckeditor/issues/133#issuecomment-352416227).
