### ISSUE TITLE
https://cdn.ckeditor.com/4.5.11/full/ckeditor.js configured from my local website

### ISSUE THREAD

**Issue by vinodn4** [chymz/ng2-ckeditor#226]
can some one help me to load from my local website instead of cdn.ckeditor.com/4.5.11
<script src="https://cdn.ckeditor.com/4.5.11/full/ckeditor.js"></script>

i have downloaded and try as a normal js reference file but its textboxes not showing and not working 

cdn.ckeditor is free licence or paid

**Comment by kzimny** [comment]
Instead of link to CDN script, download and save the ckeditor in your local folder. Atfer that link to your local ckeditor.js file. Look at this [answer](https://github.com/chymz/ng2-ckeditor/issues/148). If this implementation doesn't work post your code. I think you have forgotten to add the `import { FormsModule } from '@angular/forms';` to your app.module.ts component.

**Comment by kzimny** [comment]
If you are working with angular CLI try the following: #228

**Comment by vinodn4** [comment]
thanks @kzimny i kept ckeditor js in my local lib and use it then its not working and if i use live then it works if i kept local file path then again it gives me dir error so have you any idea

**Comment by kzimny** [comment]
I have no information about how your solution works and what is your configuration. Project configuration is out of the ng2-ckeditor scope. Without precise information you can not be helped.

**Comment by vinodn4** [comment]
thanks @kzimny  .it is working as expected really thanks .
can you please cdn.ckeditor is free licence or paid?

**Comment by kzimny** [comment]
I think it's free, but you can check it yourself. Please look at issue #157
