### ISSUE TITLE
Default target links

### ISSUE THREAD

**Issue by dudumanbogdan** [chymz/ng2-ckeditor#234]
Is it possible to set a default for target on links without explicitly press on "Target" tab?

**Comment by kzimny** [comment]
Search in google for "ckeditor links target".

**Comment by dudumanbogdan** [comment]
More useful as answer is to provide a solution instead of just saying "google it". For angular, I didn't found any useful links.

I will leave for the others how someone solved it using "on('dialogDefinition'... but not for angular. http://handsomedogstudio.com/ckeditor-set-default-target-blank

**Comment by kzimny** [comment]
You are looking for an out of the box solution which does not come with ckeditor and accordingly cannot come with ng2-ckeditor which is only an angular wrapper. Why don't you extend ng2-ckeditor yourself? To say "provide a solution instead of ..." is not understandable and not acceptable in open source platform. Good luck!
